### ISSUE TITLE
Genesis requires Node.js 6 or later but it's not mentioned anywhere

### ISSUE THREAD

**Issue by penberg** [jvirtanen/genesis#2]
Genesis requires Node.js 6 or later but the requirement is not mentioned anywhere.

**Comment by jvirtanen** [comment]
[Genesis Replicator](https://github.com/jvirtanen/genesis/tree/master/applications/replicator) requires Node.js 6, and this actually mentioned in the documentation as the last paragraph before the Limitations section.

If you launch Genesis itself with `vagrant up`, it installs Node.js 6 on the virtual machine that hosts the replicators (and other components of the system). In this case the only requirements are Vagrant and VirtualBox.
