### ISSUE TITLE
Add missing order books

### ISSUE THREAD

**Issue by jvirtanen** [jvirtanen/genesis#5]
Coinbase Pro has introduced the following order books:

- BCH-GBP
- ETC-BTC
- ETC-EUR
- ETC-GBP
- ETC-USD
- ETH-GBP
- LTC-GBP

Add these to Genesis as well.

**Tip.** Have a look at commits https://github.com/jvirtanen/genesis/commit/ddf73780c17ad5d02ab613d8dac3c00a6d11483c and https://github.com/jvirtanen/genesis/commit/214fc851729c8d24cdde0422a727a05a0586005a for an example.

**Comment by FndNur1Labs** [comment]
means we need run wallet for test this. and this port seems like

https://github.com/jvirtanen/genesis/blob/master/applications/replicator/etc/example.sh

**Comment by jvirtanen** [comment]
Furthermore, the following order books have been added:
- ZRX-BTC
- ZRX-EUR
- ZRX-USD
- BTC-USDC
- ETH-USDC

With all these markets, perhaps it would make sense for Genesis by default to only provide the USD and crypto markets instead of the EUR and GBP markets as well.

**Comment by jvirtanen** [comment]
Now Genesis by default provides only the following order books:

  - BTC-USD
  - ETH-USD
  - ETH-BTC

This was implemented in 52a0bc23942126e115299af4934ac8b0fbf57870.
